[keyboard]
name = "Ergohaven Trackball Royale"
product_name = "Trackball Royale"
vendor_id = 0xE126
product_id = 0x00C3
manufacturer = "Ergohaven"
chip = "nrf52840"

[host]
vial_enabled = true
unlock_keys = [[0, 0], [0, 1]]

[event]
action.channel_size = 16
action.subs = 2
keyboard.subs = 4

[layout]
rows = 3
cols = 2
matrix_map = """
(0,0) (0,1)
(1,0) (1,1)
(2,0) (2,1)
"""
layers = 4

[[layer]]
name = "Mouse"
keys = """
MouseBtn1  MO(2)
MO(1)  MouseBtn2
User0  User5
"""

[[layer]]
name = "Scroll"
keys = """
_  _
_  _
_  _
"""

[[layer]]
name = "Sniper"
keys = """
_  _
_  _
_  _
"""

[[layer]]
name = "Adjust"
keys = """
User10  User11
User12  User13
User7   User8
"""

[ble]
enabled = true

[matrix]
matrix_type = "direct_pin"
direct_pins = [
    ["P0_28", "P0_03"],
    ["P1_11", "P1_10"],
    ["P0_01", "P0_00"]
]

[[input_device.pmw3610]]
name = "trackball0"
spi.instance = "bitbang0"
spi.sck = "P0_08"
spi.mosi = "P0_17"
spi.miso = "P0_17"
spi.cs = "P0_13"
motion = "P0_15"
cpi = 1000
swap_xy = true
invert_x = true
invert_y = true

[storage]
clear_storage = false

[rmk]
combo_max_num = 32
morse_max_num = 32
macro_space_size = 2048
ble_profiles_num = 5

[workspace]
members = ["."]
