[keyboard]
name = "Ergohaven K:04 Qube"
product_name = "K:04"
vendor_id = 0xE126
product_id = 0x0071
manufacturer = "Ergohaven"
chip = "nrf52840"

[host]
vial_enabled = true
unlock_keys = [[0, 5], [0, 4]]

[rmk]
split_peripherals_num = 2
split_central_sleep_timeout_seconds = 120
combo_max_num = 32
morse_max_num = 32
macro_space_size = 2048
ble_profiles_num = 5

[ble]
enabled = true

[storage]
clear_storage = false
clear_layout = false

[event]
action.channel_size = 16
action.subs = 2
keyboard.subs = 4
peripheral_battery.pubs = 2
peripheral_battery.subs = 4
layer_change.channel_size = 4
layer_change.subs = 6
modifier.channel_size = 8
modifier.subs = 6

[split]
connection = "ble"
backend = "qube"

[split.central]
rows = 0
cols = 0
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "direct_pin"
direct_pins = []

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 0

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P1_13", "P0_28", "P0_03", "P1_10", "P1_11"]
col_pins = ["P1_06", "P1_04", "P1_02", "P1_00", "P0_22", "P0_20"]

[[split.peripheral.input_device.encoder]]
pin_a = "P0_10"
pin_b = "P0_09"
phase = "resolution"
resolution = 2
internal_pullup = true

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 5
col_offset = 0

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P1_13", "P0_28", "P0_03", "P1_10", "P1_11"]
col_pins = ["P1_06", "P1_04", "P1_02", "P1_00", "P0_22", "P0_20"]

[[split.peripheral.input_device.encoder]]
pin_a = "P0_10"
pin_b = "P0_09"
phase = "resolution"
resolution = 2
internal_pullup = true

[layout]
rows = 10
cols = 6
layers = 16
matrix_map = """
(0,5,L) (0,4,L) (0,3,L) (0,2,L) (0,1,L) (0,0,L)                    (5,0,R) (5,1,R) (5,2,R) (5,3,R) (5,4,R) (5,5,R)
(1,5,L) (1,4,L) (1,3,L) (1,2,L) (1,1,L) (1,0,L)                    (6,0,R) (6,1,R) (6,2,R) (6,3,R) (6,4,R) (6,5,R)
(2,5,L) (2,4,L) (2,3,L) (2,2,L) (2,1,L) (2,0,L)                    (7,0,R) (7,1,R) (7,2,R) (7,3,R) (7,4,R) (7,5,R)
(3,5,L) (3,4,L) (3,3,L) (3,2,L) (3,1,L) (3,0,L) (4,0,L)    (9,0,R) (8,0,R) (8,1,R) (8,2,R) (8,3,R) (8,4,R) (8,5,R)
                  (4,5,L) (4,4,L) (4,3,L) (4,2,L) (4,1,L)    (9,1,R) (9,2,R) (9,3,R) (9,4,R) (9,5,R)
"""

[[layer]]
name = "Base"
keys = """
Grave   Kc1   Kc2   Kc3   Kc4   Kc5   Kc6   Kc7   Kc8   Kc9   Kc0   Backspace
Escape  Q     W     E     R     T     Y     U     I     O     P     Backslash
Tab     A     S     D     F     G     H     J     K     L     Semicolon  Quote
LShift  Z     X     C     V     B     _              _             N  M  Comma  Dot  Slash  RShift
Delete  LGui  LCtrl MO(1) Space Enter MO(2) RAlt LeftBracket RightBracket
"""
encoders = [["AudioVolUp","AudioVolDown"],["AudioVolUp","AudioVolDown"]]

[[layer]]
name = "Nav"
keys = """
F1            F2              F3    F4    F5     F6      F7  F8   F9   F10  F11  F12
MediaPrevTrack MediaNextTrack Home  Up    End    Insert  _   Kc7  Kc8  Kc9  _    CapsLock
AudioMute     MediaPlayPause  Left  Down  Right  Enter   _   Kc4  Kc5  Kc6  _    CapsWordToggle
AudioVolDown  AudioVolUp      _     _     _      Delete  _   _    PrintScreen Kc1 Kc2 Kc3 _ _
PageUp        PageDown        _     _     _      _       MO(3) _    Kc0  _
"""
encoders = [["AudioVolUp","AudioVolDown"],["AudioVolUp","AudioVolDown"]]

[[layer]]
name = "Symbols"
keys = """
_  _              SHIFTED(Kc2) SHIFTED(Kc4)      SHIFTED(Kc3)  _              _            _                   SHIFTED(Kc6)    _             _              _
_  _              SHIFTED(Comma) Equal           SHIFTED(Dot)  Grave          _            LeftBracket         SHIFTED(Minus)  RightBracket  _              _
_  Backslash      SHIFTED(Kc9)   Minus           SHIFTED(Kc0)  SHIFTED(Equal) SHIFTED(Kc5) SHIFTED(LeftBracket) Semicolon       SHIFTED(RightBracket) SHIFTED(Kc1) _
_  _              SHIFTED(Kc8)   SHIFTED(Semicolon) Slash      _              _            _                   _               SHIFTED(Backslash) SHIFTED(Grave) SHIFTED(Kc7) _ _
_  _              _              MO(3)           _             _              _            _                   _               _
"""
encoders = [["AudioVolUp","AudioVolDown"],["AudioVolUp","AudioVolDown"]]

[[layer]]
name = "Adjust"
keys = """
Bootloader  _      _  _  _  _  User19 User20 User21 User22 User23 User26
_           _  _  _  _  _  _    _    _    _    _    _
_           _  _  _  _  _  _ _ _ _    _    _
_           _  _  _  _  _  _    _    _ _    _    _  _  _
_   _   _              _               _              _   _   _            _               _
"""
encoders = [["AudioVolUp","AudioVolDown"],["AudioVolUp","AudioVolDown"]]

[[layer]]
name = "Pointing"
keys = """
_  _      _          _          _          _      _      _          _          _          _      _
_  _      _          _          _          _      _      _          _          _          _      _
_  User29  MouseBtn3  MouseBtn2  MouseBtn1  User28  User28  MouseBtn1  MouseBtn2  MouseBtn3  User29  _
_  _      _          _          _          User30  _      _          User30     _          _      _  _  _
_  _  _          _          _          _   _  _          _          _
"""
encoders = [["MouseWheelDown","MouseWheelUp"],["MouseWheelDown","MouseWheelUp"]]
